### DISCUSSION TITLE
Is there anyway to make the toolbar wider?

### DISCUSSION THREAD

**Discussion by Moyf** [chrisgurney/obsidian-note-toolbar#115] [Q&A] [answered]
![image](https://github.com/user-attachments/assets/d4364a64-c81e-4d4c-86ed-e1509d254abf)

For now it seems to be limited in line width(700px)
How could I make it wider, like 900px?

**Comment by Moyf** [comment, marked as answer]
Found out by myself:

```css
/* Adjust the width (+300px) */
& .cg-note-toolbar-callout {
    margin-inline: auto auto;
    max-width: calc(var(--file-line-width)+300px) !important;
    max-width: 100%;
    /* transition: border-top 0.5s ease-out; */
}
```
