### DISCUSSION TITLE
Light-up your pinned tab icon

### DISCUSSION THREAD

**Discussion by laktiv** [chrisgurney/obsidian-note-toolbar#161] [Show and tell]
A little tweak for your toolbar if you are using "pin tab" button. Adding this to your snippet CSS will change "pin tab" icon to crossed pin and changed the color to highlight that your current tab is pinned.
![image](https://github.com/user-attachments/assets/c0cdceb2-a0d5-44e7-9384-616f121af557)

1. If you are using the button with URI `obsidian://note-toolbar?command=workspace%3Atoggle-pin`
```css
.workspace-tab-header-container:has(.is-active .mod-pinned) + .workspace-tab-container .cg-note-toolbar-container {
	[data-toolbar-link-attr-commandid][href$=toggle-pin] svg {
		/* change icon to pin-off */
		-webkit-mask-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='none' stroke='currentColor' stroke-width='2' d='M12 17v5m3-12.66V7a1 1 0 0 1 1-1a2 2 0 0 0 0-4H7.89M2 2l20 20M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11'/%3E%3C/svg%3E");
		/* change the color of pin-off icon */
		background-color: var(--text-accent);
		stroke: var(--text-accent);
	}
}
```

2. This one could be used if you pick the command from the command list. The second string should be changed with your assigned name `aria-label="Pin tab"`. I also delete a part with icon changing if you don't want to do it.
```css
.workspace-tab-header-container:has(.is-active .mod-pinned) + .workspace-tab-container .cg-note-toolbar-container {
	[aria-label="Pin tab"] svg {
		stroke: var(--text-accent);
	}
}
```

**Comment by laktiv** [comment]
And, of course, you could shorten pinned tab like the browsers do:
```css
/*= Short pinned tab =*/
.workspace-tab-header:has(.mod-pinned) {
	max-width: 55px !important;
}
```
