### DISCUSSION TITLE
Proposition: Add extra field to settings to see visibility settings

### DISCUSSION THREAD

**Discussion by laktiv** [chrisgurney/obsidian-note-toolbar#175] [Ideas]
Hi @chrisgurney,
A bit more serious proposition, in comparison to button's border. :)
Every element of the panel has 3 options:
1. Show/hide on PC/Mob with 2 params each
![image](https://github.com/user-attachments/assets/f5b1477d-ce22-4a6f-af69-72a8659fe783)
2. Position while display
![image](https://github.com/user-attachments/assets/79bf922a-4d28-463e-88aa-2dcde6984b71)
3. Style of element
![image](https://github.com/user-attachments/assets/3883f286-0b9e-4b32-b9dd-0ef8c5a58ee7)

But there is no place to see will the element be visible on Mobile, and when you have panel-as-menu structure it's easy to make a mistake in main panel (general use for most notes). Also, it is hard to see the position of panel on different devices for the same reason - it's available only in edit of this specific element (panel).

My solution propositions:
1. Add icons to elements list at edit menu (add only if element is hidden?)
![image](https://github.com/user-attachments/assets/8a91da29-6645-493f-9fa8-19f5064c2b7d)
2. Maybe it would be helpful to add status to some panels that this is internal menu and do not apply all this position-style settings to it?
![image](https://github.com/user-attachments/assets/4d212628-278c-425d-95cd-d0e57a02c924)
3. Combine settings which could be combined - example: hide on device (element), hide as position of panel, autohide at style.
4. Make style menu simpler by disabling ability to pick controversial element
![image](https://github.com/user-attachments/assets/c442e72b-1c11-488a-848c-230e120f8424)
5. Add "preview as on other device" function to test while setup.

Also, maybe #1 could be applied to "panel position" as well, not only "visibility". But I guess the general conception should be picked as a first step, before making the changes everywhere.

Hope it would be helpful fot further development and popularisation of note-toolbar.

PS: Sorry for Ukraininan. made screens before text, and saw the fail only while typing this text. If I need to reupload some images, please just let me know.

**Comment by chrisgurney** [comment]
@laktiv I think you're one step ahead of me here. 😀

1. I've been thinking I will move the _Position_ section into the mappings section, as it will help with allowing multiple toolbars per note. 
     - This could allow for a "global navigation" to show on the Home note in a prominent position, and be in the floating button in other notes, for example.
2. I also have an item on my list to remove items from the Style menu that are not applicable, depending on other options:
    - [ ] float left/right (only apply in callouts)
    - [ ] sticky, if position != props
    - [ ] editor width, if position != top (fixed)
    - [ ] content width, if position != top (fixed)

I appreciate your other suggestions as well -- will provide some food for thought!

**Reply by laktiv** [reply]
> I've been thinking I will move the _Position_ section into the mappings section, as it will help with allowing multiple toolbars per note.
> * This could allow for a "global navigation" to show on the Home note in a prominent position, and be in the floating button in other notes, for example.

Oh yes. I'm waiting for it so much.

Will wait for the further updates. But I understand it won't be soon

**Reply by laktiv** [reply]
Meanwhile - my temp idea:

```css
/* Disable dropdown options */
.note-toolbar-setting-item-style {
	/* sticky || mstcky || autohide || mnflt */
	&:has(.setting-item-name:is(
			[aria-label$="sticky"],[aria-label$="mstcky"],
			[aria-label$="autohide"],
			[aria-label$="mnflt"]
	)) select.dropdown {
		option:is([value^="float"], [value^="mflt"]) {
			display: none;
		}
	}
}
```
![image](https://github.com/user-attachments/assets/21f34767-faad-41a7-bdf9-7c3ecb301729)


```css
/* Highlight potential conflict options */
.note-toolbar-setting-item-style {
	&:has(.setting-item-name:is([aria-label$="floatl"],[aria-label$="floatr"],[aria-label$="mfltl"],[aria-label$="mfltr"])) select.dropdown {
		option:is(
			[value="autohide"],
			[value="sticky"],[value$="stcky"],
			[value="mnflt"],
			[value="wide"],[value$="wd"],
			[value="button"],[value$="mbtn"],
			[value="border"],[value$="brder"],
			[value="left"],[value="right"],[value="center"],[value="even"],[value="between"],
			[value="mlft"],[value="mrght"],[value="mctr"],[value="mevn"],
			[value$="mbtwn"]
		) {
			background-color: rgba(233, 49, 71, 0.1);
		}
	}
}
```
![image](https://github.com/user-attachments/assets/64222658-103c-4425-b662-fffe1b1f0efe)


```css
/* Warn if selected conflict styles */
.note-toolbar-setting-item-style {
	/* center || mctr */
	&:has(.setting-item-name:is([aria-label$="center"],[aria-label$="mctr"])) {
		.setting-item:has(.setting-item-name:is([aria-label$="left"],[aria-label$="mlft"],[aria-label$="right"],[aria-label$="mrght"])) {
			border-color: var(--text-error) !important;
		}
	}
	/* left || mlft */
	&:has(.setting-item-name:is([aria-label$="left"],[aria-label$="mlft"])) {
		.setting-item:has(.setting-item-name:is([aria-label$="center"],[aria-label$="mctr"],[aria-label$="right"],[aria-label$="mrght"])) {
			border-color: var(--text-error) !important;
		}
	}
	/* right || mrght */
	&:has(.setting-item-name:is([aria-label$="right"],[aria-label$="mrght"])) {
		.setting-item:has(.setting-item-name:is([aria-label$="center"],[aria-label$="mctr"],[aria-label$="left"],[aria-label$="mlft"])) {
			border-color: var(--text-error) !important;
		}
	}
}
```
![image](https://github.com/user-attachments/assets/fb62391b-353b-40cb-a6c1-b54ca530f745)
