### DISCUSSION TITLE
[CSS] Share a simple and elegant toolbar Style (cMenu-like)

### DISCUSSION THREAD

**Discussion by Moyf** [chrisgurney/obsidian-note-toolbar#201] [Show and tell]
> Disclaimer: the author of this style is @PandaNocturne
> Glory to the pandas 🐼

## Style Demo
![image](https://github.com/user-attachments/assets/ee435b9b-1bee-41a5-9ce1-5a70b84b5d9f)

It sits the toolbar below the note and takes up less space for display.

## Description
1. The toolbar name should include keyword `cmenu`
![image](https://github.com/user-attachments/assets/243ec2de-d9f9-42db-a0ef-786a03e833a9)
2. The `Sticky` style option cannot be checked
3. Position settings should be `Top (Fixed)`

![image](https://github.com/user-attachments/assets/1a2bc2b6-1ec4-4d99-9cef-bf41322e4485)

## Code file

Gist：https://gist.github.com/Moyf/796a1aeeb7aa3dd34a13d138e747a841

```css
/* Note Toolbar 像 Cmenu那样显示 */
div[data-name *="cmenu"] {
  z-index: var(--layer-status-bar);
  position: absolute;
  bottom: 60px;
  width: 100% !important;
  pointer-events: none !important;
  display: flex;
  justify-content: center !important;
  background-color: transparent !important;

  div.callout, .callout-content {
    background-color: transparent !important;
    border: 0 !important;
    margin: 0 !important;
    opacity: 1 !important;
    /* width: fit-content;
    height: fit-content; */
  }

  ul[role="menu"] {
    pointer-events: auto !important;

    width: fit-content;
    max-width: 460px;
    /* display: grid !important;
    grid-template-columns: repeat(10, minmax(0, 1fr)); */
    display: flex;
    flex-flow: row wrap;
    justify-content: flex-start;
    gap: 8px 5px !important;

    padding: 10px !important;
    transition: 200ms ease;
    height: auto;
    min-width: fit-content;
    border-radius: 6px;

    z-index: var(--layer-status-bar);
    box-shadow: 0px 3px 30px rgb(31 38 135 / 15%);
    margin: 33px !important;
    border: 1px solid var(--background-modifier-border);

    /* 添加毛玻璃效果 */
    backdrop-filter: blur(10px);
    /* background-color: rgba(255, 255, 255, 0.1) !important; */
    background-color: rgba(var(--primary-background), 0.1);

    li {
      border-radius: 6px;
      background-color: var(--background-secondary);

      &>span {
        width: 40px;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 6px !important;

        svg {
          transform: scale(1.2);
        }

      }

      .cg-note-toolbar-item-label {
        display: none;
      }
    }

  }

}
```

## Notes
Developers @chrisgurney can incorporate it into NTB as one of the default styles if you want  :D

**Comment by chrisgurney** [comment]
Very cool, thanks for sharing!

**Comment by laktiv** [comment]
Additional warning - this method has bug. If press the NTB's button which will forward you to other note (e.g. by link) and then you will press "Back" (`?command=app:go-back`) the panel will disappear. I've found in the code, but visually it will appear only after reloading the note.
![image](https://github.com/user-attachments/assets/1a52f31b-37a4-444d-bfc5-27fac08b5dd2)

Btw, in latest beta 1.16-13 there is custom css classes support. You don't need to add `-text` to name, you could select by class
```css
.cg-note-toolbar-callout.cmenu {}
```
Now it's possible to combine classes for various cases without complex coding. Below example: if add second class to toolbar (`labels`) it will show the button labels.
```css
.cg-note-toolbar-callout.cmenu:not(.labels) ul[role=menu] {
  .cg-note-toolbar-item-label { display: none; }
}
.cg-note-toolbar-callout.cmenu.labels ul[role=menu] {
  .cg-note-toolbar-item-label { white-space: wrap; }
}
```
