### DISCUSSION TITLE
Can I display frontmatter propertys in the note toolbar

### DISCUSSION THREAD

**Discussion by KingOfSpades** [chrisgurney/obsidian-note-toolbar#354] [Q&A] [answered]
I want to show certain property's in my note toolbar. I want this so I can hide the complete frontmatter block and have some key elements visible in the bar like `tags` (could be more then 1) and custom fields I use like `type` and `parents`.

Example of a frontmatter:

```yaml
---
title: "These are some type of shoes"
parents: [[Schoes]]
type: note
tags: #footwear
---

Note about a certain type of shoe. The derby.
```

Could render in the note toolbar like:

```bar
| Schoes | Note | #Footwear |
```

I tried geting it done with Dataview and these kinds of querys `$= this.tags` but I can't get it to render as the tooltip.
