### DISCUSSION TITLE
Ability to Auto-Hide the Toolbar

### DISCUSSION THREAD

**Discussion by chrisgurney** [chrisgurney/obsidian-note-toolbar#66] [Ideas]
From @fredjoe7

> Can the toolbar be made to auto-hide?
> 
> When the mouse cursor is not positioned over the note toolbar, or when the note toolbar focus command is not activated, it should be set to auto-hide to prevent obstructing the view of the note. This feature would be particularly beneficial for desktop users with smaller displays, optimizing their workspace. This will be good for desktop devices, not mobile devices.
> 
> I used an this plugin called editing toolbar and its autohide features were useful.
> 
> https://github.com/PKM-er/obsidian-editing-toolbar

_Originally posted by @fredjoe7 in https://github.com/chrisgurney/obsidian-note-toolbar/issues/65#issuecomment-2099021672_

**Comment by FelipeRearden** [comment]
@chrisgurney and @fredjoe7 

Maybe this snippet could be helpful to achieve the auto hide 🙏

```css
.callout[data-callout="note-toolbar"] {
	border-bottom: 1px solid transparent !important;
}

.callout[data-callout="note-toolbar"] .callout-content span {
	color: transparent !important;
}

.callout[data-callout="note-toolbar"]:hover .callout-content span {
	color: var(--icon-color) !important;
}

.callout[data-callout="note-toolbar"] .callout-content:focus-within span {
	color: var(--icon-color) !important;
}

.callout[data-callout="note-toolbar"]:hover {
	border-bottom: 1px solid var(--hr-color) !important;
}

.callout[data-callout="note-toolbar"]:focus-within {
	border-bottom: 1px solid var(--hr-color) !important;
} 
```
