### ISSUE TITLE
Double-bolded icons

### ISSUE THREAD

**Issue by laktiv** [chrisgurney/obsidian-note-toolbar#162]
**Description of the bug**
Icons in callout's toolbar have doubled "stroke-width" attribute which makes icon very bold.

This snipped fix it:
```css
.cm-callout [data-callout="note-toolbar"] .cm-iconize-icon svg svg[stroke-width='16px'] {
  stroke-width: 2;
} 	/*/ Fix very bold icons */
```

**Expected behavior**
Regular icon's bold.

**Screenshots (if you think it will help)**
Compared to toolbar Fixed top (above):
![](https://i.imgur.com/7oJAtd0.png)

Callout in note:
![](https://i.imgur.com/AS1UnnX.png) 
![](https://i.imgur.com/bWBr3Z0.png)

**Desktop environment:**
 - OS: Windows 11
 - Obsidian version: 1.7.4
 - Note Toolbar version: 1.14.3

**Comment by chrisgurney** [comment]
@laktiv Thank you! I noticed this but wasn't quite sure what was going on here. I'll patch in your fix for now. Appreciate it!

**Comment by chrisgurney** [comment]
@laktiv Fixed in [1.14.4](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.14.4). Thanks again!

**Comment by laktiv** [comment]
@chrisgurney sure, but later.
I'm checking other noted bugs and want to publish them. One already fixed not in beta, checking others.

**Comment by laktiv** [comment]
Not worked with callouts. Example callout in note:
```md
> [!note-toolbar|even|border]
> ```dataview
> LIST WHERE file.starred SORT file.name
> ```
```

Fix that solves the issue:
```css
[data-callout="note-toolbar"] svg[stroke-width='16px'] {
	stroke-width: 2;
}
```
