### ISSUE TITLE
gap when scrolling

### ISSUE THREAD

**Issue by imeed166** [chrisgurney/obsidian-note-toolbar#18]
**Description of the bug**
there is a gap when scrolling on a long note, 

**Steps to reproduce**

1. create long note
2. add buttons to toolbar
3. scroll 

**Expected behavior**

there is no gap

**Screenshots (if you think it will help)**

![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/38974541/ab1bae75-18f3-42a0-b660-1e1e1ebd0a6c)

**Plugin links (if applicable to the issue):**

**Desktop environment:**
 - OS: mac os 12.3.1
 - Obsidian version: 1.5.11
 - Note Toolbar version: 1.4.7

**Mobile environment (if applicable to the issue):**
 - Device: 
 - OS: 
 - Obsidian version: 
 - Note Toolbar version: 

**Additional context**
_Add any other context about the problem here._

**Comment by chrisgurney** [comment]
Hello! Thanks for the report.

Are you using any specific themes?

**Comment by imeed166** [comment]
I've confirmed it's because of the css snippet i'm using. 
```css
body {
    --h1-color: var(--header-imed);
    --h2-color: var(--header-imed);
    --h3-color: var(--header-imed);
    --h4-color: var(--header-imed);
    --h5-color: var(--header-imed);
    --h6-color: var(--header-imed);
    --h1-font: inherit;
    --h2-font: inherit;
    --h3-font: inherit;
    --h4-font: inherit;
    --h5-font: inherit;
    --h6-font: inherit;
    --h1-line-height: 1.2;
    --h2-line-height: 1.2;
    --h3-line-height: 1.3;
    --h4-line-height: 1.4;
    --h5-line-height: var(--line-height-normal);
    --h6-line-height: var(--line-height-normal);
    --h1-size: 1em;
    --h2-size: 1em;
    --h3-size: 1em;
    --h4-size: 1em;
    --h5-size: 1em;
    --h6-size: 1em;
    --h1-style: normal;
    --h2-style: normal;
    --h3-style: normal;
    --h4-style: normal;
    --h5-style: normal;
    --h6-style: normal;
    --h1-variant: normal;
    --h2-variant: normal;
    --h3-variant: normal;
    --h4-variant: normal;
    --h5-variant: normal;
    --h6-variant: normal;
    --h1-weight: bold;
    --h2-weight: bold;
    --h3-weight: bold;
    --h4-weight: bold;
    --h5-weight: bold;
    --h6-weight: bold;
    --list-indent: 2em;
    --list-spacing: 0.075em;
    --list-marker-color: var(--text-faint);
    --list-marker-color-hover: var(--text-muted);
    --list-marker-color-collapsed: var(--text-accent);
    --list-bullet-border: none;
    --list-bullet-radius: 30%;
    --list-bullet-size: 4px;
    --list-bullet-transform: none;
}

.theme-dark {
    --header-imed: white;
} 
.theme-light {
    --header-imed: dark;
}
```

Also i found that the toggle list are not hidden by the sticky toolbar, even if i disable the css snippet.


![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/38974541/d2c3f2ca-095b-4172-80a1-2000af1a01d2)
